config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#top'

  resources :teachers
  resources :students
  resources :parents
  resources :teacher_sessions
  resources :student_sessions
  resources :parent_sessions
  resources :teacher_boards
  resources :contracts
  get "/signup", to: "signup#signup"
  get "/login", to: "login#login"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contract.rb
class Contract < ApplicationRecord
  belongs_to :teacher_board
  belongs_to :parent
end

app/models/parent.rb
class Parent < ApplicationRecord
  has_many :contracts
  has_many :teacher_boards, through: :contracts

  has_secure_password
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :parent

  has_secure_password
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_many :teacher_boards, dependent: :destroy

  has_secure_password
end

app/models/teacher_board.rb
class TeacherBoard < ApplicationRecord
  belongs_to :teacher
  has_many :contracts
  has_many :parents, through: :contracts
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def login
  end
end

app/controllers/parents_controller.rb
class ParentsController < ApplicationController
  include TeacherSessionsHelper

  def new
    @parent = Parent.new
  end

  def show
    @parent = Parent.find(params[:id])
  end

  def create
    @parent = Parent.new(parent_params)

    if @parent.save
      log_in(@parent)
      redirect_to parent_path @parent.id
    else
      render :new
    end
  end

  private

    def parent_params
      params.require(:parent).permit(:name, :email, :password, :password_confirmation)
    end
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
  def signup
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contract_helper.rb
module ContractHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/parent_sessions_helper.rb
module ParentSessionsHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teacher_boards_helper.rb
module TeacherBoardsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PracticeKatekyoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/header" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_header.html.erb
<div class="header">
  <div class="header-main">
    <div class="header-title"><%= link_to "アプリ", root_path if !logged_in? %></div>
    <% if logged_in? %>
      <% if teacher_controller? %>
        <div class="header-title">
          <%= link_to "アプリ", teacher_path(current_user.id) %>
        </div>
      <% elsif student_controller? %>
        <div class="header-title">
          <%= link_to "アプリ", student_path(current_user.id) %>
        </div>
      <% else parent_controller? %>
        <div class="header-title">
          <%= link_to "アプリ", parent_path(current_user.id) %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="header-right">
    <% if logged_in? %>
      <%= link_to "生徒募集掲示板を見る", teacher_boards_path %>
      <%= link_to "講師募集掲示板を見る" %>
      <% if teacher_controller? %>
        <%= link_to "ログアウト", teacher_session_path(current_user.id), method: :delete %>
      <% elsif student_controller? %>
        <%= link_to "ログアウト", student_session_path(current_user.id), method: :delete %>
      <% else parent_controller? %>
        <%= link_to "ログアウト", parent_session_path(current_user.id), method: :delete %>
      <% end %>
    <% else %>
      <ul class="header-list">
        <li><%= link_to "サインアップ", signup_path %></li>
        <li><%= link_to "ログイン", login_path %></li>
      </ul>
    <% end %>
  </div>
</div>