config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#top'

  resources :teachers
  resources :students
  resources :parents
  resources :teacher_sessions
  resources :student_sessions
  resources :parent_sessions
  resources :teacher_boards
  resources :contracts
  get "/signup", to: "signup#signup"
  get "/login", to: "login#login"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contract.rb
class Contract < ApplicationRecord
  belongs_to :teacher_board
  belongs_to :parent
end

app/models/parent.rb
class Parent < ApplicationRecord
  has_many :contracts
  has_many :teacher_boards, through: :contracts

  has_secure_password
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :parent

  has_secure_password
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_many :teacher_boards, dependent: :destroy

  has_secure_password
end

app/models/teacher_board.rb
class TeacherBoard < ApplicationRecord
  belongs_to :teacher
  has_many :contracts
  has_many :parents, through: :contracts
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def login
  end
end

app/controllers/parents_controller.rb
class ParentsController < ApplicationController
  include TeacherSessionsHelper

  def new
    @parent = Parent.new
  end

  def show
    @parent = Parent.find(params[:id])
  end

  def create
    @parent = Parent.new(parent_params)

    if @parent.save
      log_in(@parent)
      redirect_to parent_path @parent.id
    else
      render :new
    end
  end

  private

    def parent_params
      params.require(:parent).permit(:name, :email, :password, :password_confirmation)
    end
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
  def signup
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  include TeacherSessionsHelper

  def new
    @student = Student.new
  end

  def show
    @student = Student.find(params[:id])
  end

  def create
    @parent = Parent.find_by(email: student_params[:parent_email])
    student = Student.new(student_params)
    @student = Student.new(
      name: student.name,
      email: student.email,
      password: student.password,
      password_confirmation: student.password_confirmation,
      school: student.school,
      parent_email: student.parent_email,
      parent_id: @parent.id)

    if @student.save
      log_in(@student)
      redirect_to student_path(@student.id)
    else
      render :new
    end
  end

  private

    def student_params
      params.require(:student).permit(:name, :email, :password, :password_confirmation,:school, :parent_email)
    end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  include TeacherSessionsHelper


  def index
  end

  def show
    @teacher = Teacher.find(params[:id])
    @teacher_boards = @teacher.teacher_boards.all
  end

  def new
    @teacher = Teacher.new
  end

  def create
    @teacher = Teacher.new(teacher_params)
    
    if @teacher.save
      log_in(@teacher)
      redirect_to teacher_path @teacher.id
    else
      render :new
    end
  end

  
  
  private
  
  def teacher_params
    params.require(:teacher).permit(:name, :email, :password, :password_confirmation, :school, :self_introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contract_helper.rb
module ContractHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/parent_sessions_helper.rb
module ParentSessionsHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/student_sessions_helper.rb
module StudentSessionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teacher_boards_helper.rb
module TeacherBoardsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/parents/new.html.erb
<h2>保護者用の登録ページ</h2>

<%= form_with model: @parent do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :password %>
    <%= f.text_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.text_field :password_confirmation %>
  </div>
  <%= f.submit "送信"%>
<% end %>

app/views/parents/show.html.erb
<%= @parent.name %>
<%= @parent.email%>

app/views/students/new.html.erb
<h2>生徒用の登録ページ</h2>

<%= form_with model: @student do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :password %>
    <%= f.text_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.text_field :password_confirmation %>
  </div>
  <div>
    <%= f.label :school %>
    <%= f.text_field :school %>
  </div>
  <div>
    <%= f.label :parent_email %>
    <%= f.text_field :parent_email %>
  </div>
  <%= f.submit "送信"%>
<% end %>

app/views/students/show.html.erb
ログインしているのは<%= @student.name %>です
親は<%= @student.parent.name %>です

app/views/teachers/new.html.erb
<h2>先生用の登録ページ</h2>

<%= form_with model: @teacher do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :password %>
    <%= f.text_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.text_field :password_confirmation %>
  </div>
  <div>
    <%= f.label :school %>
    <%= f.text_field :school %>
  </div>
  <div>
    <%= f.label :self_introduction %>
    <%= f.text_field :self_introduction %>
  </div>
  <%= f.submit "送信"%>
<% end %>

app/views/teachers/show.html.erb
<h2>Teahcer IDは<%= current_user.id %>です</h2>
<p>名前は<%= current_user.name %>です</p>
<div>
  <%= link_to "生徒募集掲示板を作る", new_teacher_board_path %>
</div>

<% @teacher_boards.each do |board| %>
  <div class="board-container">
    <div>
      授業タイトル: <%= board.title %>
    </div>
    <div>
      値段: <%= board.price %>
    </div>
    <div>
      授業内容: <%= board.content %>
    </div>
    <div>
      教科: <%= board.subject %>
    </div>
    <div>
      先生: <%= board.teacher.name %>
    </div>
  </div>
<% end %>